# Generated by Django 5.1.8 on 2025-04-20 02:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
