# Generated by Django 5.1.8 on 2025-04-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_magazineorderpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazineorderpage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='magazineorderpage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='magazineorderpage',
            name='state',
        ),
        migrations.RemoveField(
            model_name='magazineorderpage',
            name='subscription_term',
        ),
        migrations.RemoveField(
            model_name='magazineorderpage',
            name='zip_code',
        ),
    ]
