# Generated by Django 5.1.8 on 2025-06-11 18:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_cdsformpage"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexibleLayoutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("heading", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter the heading text to display.",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("heading_text", 0)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Flexible Layout Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
